<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <LangVersion>latest</LangVersion>
    <TargetFramework>net48</TargetFramework>
  </PropertyGroup>

  <PropertyGroup>
    <Configurations>Debug;Release</Configurations>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <RestoreAdditionalProjectSources>
      https://api.nuget.org/v3/index.json;
      https://nuget.bepinex.dev/v3/index.json;
      https://nuget.samboy.dev/v3/index.json
    </RestoreAdditionalProjectSources>
    <RootNamespace>CRC3D3.NotEnoughTranslator.Plugin</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Analyzers" PrivateAssets="all" Version="1.*"/>
    <PackageReference Include="BepInEx.Core" Version="5.*"/>
    <PackageReference Include="BepInEx.PluginInfoProps" Version="2.*"/>
    <PackageReference Include="UnityEngine.Modules" IncludeAssets="compile" Version="2022.3.62"/>
    <PackageReference Include="Newtonsoft.Json" Version="13.*"/>
    <Reference Include="System.IO.Compression"/>
    <Reference Include="System.IO.Compression.FileSystem"/>
    
    <Reference Include="I2.Localization">
      <HintPath>..\lib\I2.Localization.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>..\lib\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp-firstpass">
      <HintPath>..\lib\Assembly-CSharp-firstpass.dll</HintPath>
      <Private>false</Private>
    </Reference>
    
  </ItemGroup>
  
  <PropertyGroup>
    <Authors>MeidoPromotionAssociation</Authors>
    <Company>MeidoPromotionAssociation</Company>
    <Copyright>Bsd 3-Clause License</Copyright>
    <Description>https://github.com/MeidoPromotionAssociation/CRC3D3.NotEnoughTranslator.Plugin</Description> <!-- For BepInEx.ConfigurationManager -->
    <PackageLicenseExpression>BSD-3-Clause</PackageLicenseExpression>
  </PropertyGroup>

</Project>
